{
 "title": "MOLT Dashboard",
 "description": "Dashboard for MOLT metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "schema",
    "label": "Schema",
    "query": {
     "query": "label_values({__name__=~ \"molt_fetch_source_query_duration_ms_bucket|molt_fetch_prepare_csv_file_duration_ms_bucket|molt_fetch_csv_upload_duration_ms_bucket|molt_fetch_convert_shard_data_to_datums_duration_ms_bucket|molt_fetch_write_datums_to_writer_pipe_duration_ms_bucket\"}, schema)"
    }
   },
   {
    "name": "table",
    "label": "Table",
    "query": {
     "query": "label_values({__name__=~ \"molt_fetch_rows_exported|molt_fetch_rows_imported|molt_fetch_num_data_errors|molt_fetch_table_export_duration_ms|molt_fetch_table_import_duration_ms|molt_fetch_table_overall_duration_ms|molt_fetch_completion_percent|molt_fetch_source_query_duration_ms_bucket|molt_fetch_prepare_csv_file_duration_ms_bucket|molt_fetch_csv_upload_duration_ms_bucket|molt_fetch_convert_shard_data_to_datums_duration_ms_bucket|molt_fetch_write_datums_to_writer_pipe_duration_ms_bucket\"}, table)"
    }
   },
   {
    "name": "shard",
    "label": "Shard",
    "query": {
     "query": "label_values({__name__=~ \"molt_fetch_source_query_duration_ms_bucket|molt_fetch_prepare_csv_file_duration_ms_bucket|molt_fetch_csv_upload_duration_ms_bucket|molt_fetch_convert_shard_data_to_datums_duration_ms_bucket|molt_fetch_write_datums_to_writer_pipe_duration_ms_bucket\"}, shard)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Verify Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Tables Verified",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "molt_verify_num_tables{category=\"verified\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of Tables Missing",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "molt_verify_num_tables{category=\"missing\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of Tables Extraneous",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "molt_verify_num_tables{category=\"extraneous\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Overall Verify Duration (s)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "molt_verify_duration_seconds", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Number of Rows Verified Over Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum by (table) (molt_verify_rows_read{table=~\"$table\"})",
       "legendFormat": "{{table}}"
      }
     ]
    },
    {
     "title": "Number of Rows by Row Status Over Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "sum by (table, status) (molt_verify_row_verification_status{table=~\"$table\", table != \"overall\" })",
       "legendFormat": "{{table}}-{{status}}"
      }
     ]
    }
   ]
  },
  { "title": "Fetch Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Overall  Fetch Duration (s)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "molt_fetch_overall_duration", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of Task Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "molt_fetch_num_task_errors", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Overall Duration (By Schema / Table)",
   "type": "stat",
   "gridPos": { "h": 16, "w": 9, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "molt_fetch_table_overall_duration_ms{schema=~\"$schema\",table=~\"$table\"}",
     "legendFormat": "{{schema}}.{{table}}"
    }
   ]
  },
  {
   "title": "Number of Tables",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "molt_fetch_num_tables", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of Data Errors (By Schema / Table)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "molt_fetch_num_data_errors{schema=~\"$schema\",table=~\"$table\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Export Duration (By Schema / Table) (s)",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "molt_fetch_table_export_duration_ms{schema=~\"$schema\",table=~\"$table\"}",
     "legendFormat": "{{schema}}.{{table}}"
    }
   ]
  },
  {
   "title": "Import Duration (By Schema / Table) (s)",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "molt_fetch_table_import_duration_ms{schema=~\"$schema\",table=~\"$table\"}",
     "legendFormat": "{{schema}}.{{table}}"
    }
   ]
  },
  {
   "title": "Number of Rows Exported Over Time (By Schema / Table)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum by (schema, table) (molt_fetch_rows_exported{schema=~\"$schema\",table=~\"$table\"})",
     "legendFormat": "{{schema}}.{{table}}"
    }
   ]
  },
  {
   "title": "Rate of Rows Exported Over Time (Per Schema / Table) (rows / sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum by (schema, table) (rate(molt_fetch_rows_exported{schema=~\"$schema\",table=~\"$table\"}[1m]))",
     "legendFormat": "{{schema}}.{{table}}"
    }
   ]
  },
  {
   "title": "Number of Rows Imported Over Time (By Schema / Table)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by (schema, table) (molt_fetch_rows_imported{schema=~\"$schema\",table=~\"$table\"})",
     "legendFormat": "{{schema}}.{{table}}"
    }
   ]
  },
  {
   "title": "Rate of Rows Imported Over Time (Per Schema / Table) (rows / sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "sum by (schema, table) (rate(molt_fetch_rows_imported{schema=~\"$schema\",table=~\"$table\"}[1m]))",
     "legendFormat": "{{schema}}.{{table}}"
    }
   ]
  },
  {
   "title": "Source Query Duration (By Schema / Table / Shard) (ms) [For row-batch-size records]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(molt_fetch_source_query_duration_ms_bucket{schema=~\"$schema\",table=~\"$table\",shard=~\"$shard\"}[5m]))",
     "legendFormat": "p50 - {{schema}}.{{table}}.{{shard}}"
    },
    {
     "expr": "histogram_quantile(0.75, rate(molt_fetch_source_query_duration_ms_bucket{schema=~\"$schema\",table=~\"$table\",shard=~\"$shard\"}[5m]))",
     "legendFormat": "p75 - {{schema}}.{{table}}.{{shard}}"
    },
    {
     "expr": "histogram_quantile(0.90, rate(molt_fetch_source_query_duration_ms_bucket{schema=~\"$schema\",table=~\"$table\",shard=~\"$shard\"}[5m]))",
     "legendFormat": "p90 - {{schema}}.{{table}}.{{shard}}"
    },
    {
     "expr": "histogram_quantile(0.99, rate(molt_fetch_source_query_duration_ms_bucket{schema=~\"$schema\",table=~\"$table\",shard=~\"$shard\"}[5m]))",
     "legendFormat": "p99 - {{schema}}.{{table}}.{{shard}}"
    }
   ]
  },
  {
   "title": "Convert Shard Data to Datums Duration (By Schema / Table / Shard) (ms) [For row-batch-size data]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(molt_fetch_convert_shard_data_to_datums_duration_ms_bucket{schema=~\"$schema\",table=~\"$table\",shard=~\"$shard\"}[5m]))",
     "legendFormat": "p50 - {{schema}}.{{table}}.{{shard}}"
    },
    {
     "expr": "histogram_quantile(0.75, rate(molt_fetch_convert_shard_data_to_datums_duration_ms_bucket{schema=~\"$schema\",table=~\"$table\",shard=~\"$shard\"}[5m]))",
     "legendFormat": "p75 - {{schema}}.{{table}}.{{shard}}"
    },
    {
     "expr": "histogram_quantile(0.90, rate(molt_fetch_convert_shard_data_to_datums_duration_ms_bucket{schema=~\"$schema\",table=~\"$table\",shard=~\"$shard\"}[5m]))",
     "legendFormat": "p90 - {{schema}}.{{table}}.{{shard}}"
    },
    {
     "expr": "histogram_quantile(0.99, rate(molt_fetch_convert_shard_data_to_datums_duration_ms_bucket{schema=~\"$schema\",table=~\"$table\",shard=~\"$shard\"}[5m]))",
     "legendFormat": "p99 - {{schema}}.{{table}}.{{shard}}"
    }
   ]
  },
  {
   "title": "Write Datums to Writer Pipe Duration (By Schema / Table / Shard) (ms) [For row-batch-size datums]",
   "type": "timeseries",
   "description": "Duration to write all datums from a shard to write pipe during export",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(molt_fetch_write_datums_to_writer_pipe_duration_ms_bucket{schema=~\"$schema\",table=~\"$table\",shard=~\"$shard\"}[5m]))",
     "legendFormat": "p50 - {{schema}}.{{table}}.{{shard}}"
    },
    {
     "expr": "histogram_quantile(0.75, rate(molt_fetch_write_datums_to_writer_pipe_duration_ms_bucket{schema=~\"$schema\",table=~\"$table\",shard=~\"$shard\"}[5m]))",
     "legendFormat": "p75 - {{schema}}.{{table}}.{{shard}}"
    },
    {
     "expr": "histogram_quantile(0.90, rate(molt_fetch_write_datums_to_writer_pipe_duration_ms_bucket{schema=~\"$schema\",table=~\"$table\",shard=~\"$shard\"}[5m]))",
     "legendFormat": "p90 - {{schema}}.{{table}}.{{shard}}"
    },
    {
     "expr": "histogram_quantile(0.99, rate(molt_fetch_write_datums_to_writer_pipe_duration_ms_bucket{schema=~\"$schema\",table=~\"$table\",shard=~\"$shard\"}[5m]))",
     "legendFormat": "p99 - {{schema}}.{{table}}.{{shard}}"
    }
   ]
  },
  {
   "title": "Prepare CSV File Duration (By Schema / Table / Shard) (ms) [For flush-size / flush-rows records]",
   "type": "timeseries",
   "description": "Duration to prepare a csv file ready to be written to storage",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(molt_fetch_prepare_csv_file_duration_ms_bucket{schema=~\"$schema\",table=~\"$table\",shard=~\"$shard\"}[5m]))",
     "legendFormat": "p50 - {{schema}}.{{table}}.{{shard}}"
    },
    {
     "expr": "histogram_quantile(0.75, rate(molt_fetch_prepare_csv_file_duration_ms_bucket{schema=~\"$schema\",table=~\"$table\",shard=~\"$shard\"}[5m]))",
     "legendFormat": "p75 - {{schema}}.{{table}}.{{shard}}"
    },
    {
     "expr": "histogram_quantile(0.90, rate(molt_fetch_prepare_csv_file_duration_ms_bucket{schema=~\"$schema\",table=~\"$table\",shard=~\"$shard\"}[5m]))",
     "legendFormat": "p90 - {{schema}}.{{table}}.{{shard}}"
    },
    {
     "expr": "histogram_quantile(0.99, rate(molt_fetch_prepare_csv_file_duration_ms_bucket{schema=~\"$schema\",table=~\"$table\",shard=~\"$shard\"}[5m]))",
     "legendFormat": "p99 - {{schema}}.{{table}}.{{shard}}"
    }
   ]
  },
  {
   "title": "CSV Upload Duration (By Schema / Table / Shard) (ms) [per csv file created]",
   "type": "timeseries",
   "description": "Duration to upload CSV files to storage (S3, GCP, Local)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(molt_fetch_csv_upload_duration_ms_bucket{schema=~\"$schema\",table=~\"$table\",shard=~\"$shard\"}[5m]))",
     "legendFormat": "p50 - {{schema}}.{{table}}.{{shard}}"
    },
    {
     "expr": "histogram_quantile(0.75, rate(molt_fetch_csv_upload_duration_ms_bucket{schema=~\"$schema\",table=~\"$table\",shard=~\"$shard\"}[5m]))",
     "legendFormat": "p75 - {{schema}}.{{table}}.{{shard}}"
    },
    {
     "expr": "histogram_quantile(0.90, rate(molt_fetch_csv_upload_duration_ms_bucket{schema=~\"$schema\",table=~\"$table\",shard=~\"$shard\"}[5m]))",
     "legendFormat": "p90 - {{schema}}.{{table}}.{{shard}}"
    },
    {
     "expr": "histogram_quantile(0.99, rate(molt_fetch_csv_upload_duration_ms_bucket{schema=~\"$schema\",table=~\"$table\",shard=~\"$shard\"}[5m]))",
     "legendFormat": "p99 - {{schema}}.{{table}}.{{shard}}"
    }
   ]
  }
 ]
}